database:
  url: http://localhost:8050

profile:
  url: http://localhost:8040

task:
  url: http://localhost:8081

spring:
  datasource:
    url: jdbc:postgresql://db:5432/test4
    username: admin
    password: 11111111
    driver-class-name: org.postgresql.Driver
